// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGqe04l07oUXBotYTeG0eOuKRlHHRvD1M',
    appId: '1:667372664517:web:04b9268b07dde8acf322ac',
    messagingSenderId: '667372664517',
    projectId: 'cord-bfb48',
    authDomain: 'cord-bfb48.firebaseapp.com',
    storageBucket: 'cord-bfb48.firebasestorage.app',
    measurementId: 'G-T3J43S6R46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHhK4xoz056-4Tc9HgeC1SCDxXFVjhmio',
    appId: '1:667372664517:android:e4adb80925f3dbaff322ac',
    messagingSenderId: '667372664517',
    projectId: 'cord-bfb48',
    storageBucket: 'cord-bfb48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaAO9XYzlLqb1GzTsm0OPp65XWEUUZb2M',
    appId: '1:667372664517:ios:f2397b003609367df322ac',
    messagingSenderId: '667372664517',
    projectId: 'cord-bfb48',
    storageBucket: 'cord-bfb48.firebasestorage.app',
    iosBundleId: 'com.sessionate.sessionate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGqe04l07oUXBotYTeG0eOuKRlHHRvD1M',
    appId: '1:667372664517:web:d19601a66a3c8344f322ac',
    messagingSenderId: '667372664517',
    projectId: 'cord-bfb48',
    authDomain: 'cord-bfb48.firebaseapp.com',
    storageBucket: 'cord-bfb48.firebasestorage.app',
    measurementId: 'G-FXZT862N7T',
  );
}
